version: '3'
services:
  db:
    image: postgres:11
    container_name: postgres-tempest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./dimensional_create_tables.sql:/docker-entrypoint-initdb.d/init1.sql
      - ./relational_create_table.sql:/docker-entrypoint-initdb.d/init2.sql
      - ./relational_populate_tables.sql:/docker-entrypoint-initdb.d/init3.sql
      - ./dimensional_populate_tables.sql:/docker-entrypoint-initdb.d/init4.sql
